### PR TITLE
Overriding the async methods has a real performance benefit.

### PR DESCRIPTION
**Pull request by jaredrsowers**
Overriding the async methods has a real performance benefit.

### CODE REVIEW

**Comment by cosullivan** [comment]
How did you measure the performance benefit and do you know why does it exists?

**Comment by ramonsmits** [comment]
Network communication is inherently blocking IO thus would benefit from async methods.

**Comment by reinaldocoelho** [comment]
It´s possible to create some performance tests to assert this data or validate this will work well with all features?
It´s real great if changes can bring validation too.  :-)
Did this change solve any problems for you?

**Comment by cosullivan** [comment]
The code does use Async method wherever possible, but in older versions of the framework, the Stream's async methods were simply wrapping the underlying sync methods. 

My question on the PR was that the overrides that were applied in the PR should have been doing the same thing as the default implementations anyway and therefore I didn't understand where these performance benefits were coming from.

In saying that, the EndpointStream class isn't being used anyway and the code that obsoleted that is still using the async stream methods (which are more correct in current versions of the framework).

**Pull request closed without merging**
