### PR TITLE
Added support for Proxy Protocol

### PR DESCRIPTION
**Pull request by slick-nic**
Other SMTP servers support proxy protocol [1] allowing load balancers like HAProxy to tell the server the "real" address of the client making the request.
[1] http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

I’ve tried to follow the style already in the project, but please let me know if you spot anything that can be improved. 😊

*this is the second attempt at this since I missed off adding the new Endpoints on the context interface

### CODE REVIEW

**Comment by cosullivan** [comment]
Hi @slick-nic ,

Thanks for your interest in this. I will have a look over that spec so I can understand it and then review your PR. 

I should hopefully be able to do this in the next 1-2 days.

Thanks,
Cain.

**Comment by RFlipper** [comment]
@slick-nic @cosullivan Guys, sorry to bother you, is there any news about PR?

**Comment by dohly** [comment]
I've just built and tested it on my laptop - it seems to be working. It will be nice to have it in the next version of the nuget package.

**Comment by slick-nic** [comment]
Ill take another look at this shortly and see if the conflicts resolve easily with the new master.

**Comment by cosullivan** [comment]
This is now merged and I will publish a new version shortly (7.1.0).

**Pull request merged**
