### PR TITLE
Adding new Smtp Reply codes to Enum.

### PR DESCRIPTION
**Pull request by reinaldocoelho**
Hi @cosullivan.

We need to use some other of Reply Codes on server. Including some Temporary errors.
I was include on file other reply codes based on article:
   * https://serversmtp.com/smtp-error/

Can we merge it to principal repository?

### CODE REVIEW

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

I've just done this now and will publish an updated package to Nuget later today.

Thanks,
Cain.

**Comment by reinaldocoelho** [comment]
Hi @cosullivan!
Thank you :-)

**Comment by reinaldocoelho** [comment]
Hi @cosullivan , created you a new Nuget Package with this new SMTP response list?
It is available?

**Comment by cosullivan** [comment]
Hi,

Sorry, I've just done it then v6.1.0.

Thanks,
Cain.

**Comment by bluewalk** [comment]
Hiya,

These codes are now available but there is no way yet returning these to the client connection.
Can you add the logic to `MailCommand.cs` `ExecuteAsync`-method to be able to return these or am I looking at it the wrong way?

My usecase is that I want to implement greylisting (https://tools.ietf.org/html/rfc6647) by returning code `421` so the client tries again later. Now the `MailboxFilterResult.NoTemporarily` returns `550 - mailbox unavailable` which causes the client not to try again.

Cheers

**Comment by cosullivan** [comment]
Hi @bluewalk ,

If you want to return a different code from your IMailboxFilter then you can throw an SmtpResponseException

`throw new SmtpResponseException(SmtpResponse.ServiceUnavailable);`

The StmpResponseException can be thrown from within any of the hooks to control the response to a command.

Thanks, Cain.

**Comment by bluewalk** [comment]
Hi @cosullivan 

Thanks! Will give that a try.

Have a great day!

**Pull request merged**
