### PR TITLE
Fix for #74 -- Issue #81 -- parser now supports UTF-8 encoding.

### PR DESCRIPTION
**Pull request by Jaben**
Added support for the parser to support UTF-8. Added verification tests.

### CODE REVIEW

**Comment by Jaben** [comment]
With this PR -- the feature should be workable now :)

**Comment by cosullivan** [comment]
Hi,

I had a quick look through the spec for SMTPUTF8 and I don't think PR will make it adhere completely to the spec. For example, i think the parser itself might have to change to include handling of the ABNF "UTF8-non-ascii".

There seems to be a close relationship for SMTPUTF8 and Internationalized Email Headers
https://tools.ietf.org/html/rfc6532

Thanks,
Cain.

**Comment by Jaben** [comment]
@cosullivan SMTPUTF8 & Internationalized Email Headers requires support for UTF-8 encoding on all strings -- which the parser now supports. From the RFC: 
```
3.2.  Syntax Extensions to RFC 5322

The preceding changes mean that the following constructs now allow UTF-8:
   1.  Unstructured text, used in header fields like "Subject:" or
       "Content-description:".
   2.  Any construct that uses atoms, including but not limited to the
       local parts of addresses and Message-IDs.  This includes
       addresses in the "for" clauses of "Received:" header fields.
   3.  Quoted strings.
   4.  Domains.
```

Not sure what what other changes would be required.

**Comment by cosullivan** [comment]
Thanks, I've just pushed a new version to NuGet with this change.

**Pull request merged**
