### PR TITLE
Update 354

### PR DESCRIPTION
**Pull request by AdomasL**
354 requires more than just "354" for just receiving data

### CODE REVIEW

**Comment by cosullivan** [comment]
Hi,

I'm not really sure what the point of this PR is? Is this to resolve a bug, if so what is the bug?

Thanks,
Cain.

**Comment by AdomasL** [comment]
Hello,

From my understanding the response code 354 requires further explaining on what we want form it, for example to receive or to send data. When testing your package I ran into this problem that the server would stop, because it couldn’t read the message Data, because the server didn’t give it. And from my understanding it’s because simply “354 end message…” isn’t enough, it needs a further response like “354 Receive message content”, at least it was what I used when creating my own.

Adomas

**Comment by cosullivan** [comment]
Hi,

No, that's not correct. I would suggest that it is another issue that is occurring or a very poor implementation of a Mail Transport Agent.

The reply code for a DATA command should be a 354 and all other text on that line should be ignored by the mail client.

How are you testing this, can you reproduce the issue you are seeing?

Thanks,
Cain.

**Comment by AdomasL** [comment]
Well, I basically used your sampleApp and the session would get stuck during the Data phase, not continuing any further. I figured it was an issue with the response code, as the async function kept waiting for data to read, when there was none. I’ll test it out on another server and see if it has any difference.

**Pull request closed without merging**
